// <auto-generated />
namespace RSPNMISv2.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class PartnerOganizationisNullableinOutreach : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(PartnerOganizationisNullableinOutreach));
        
        string IMigrationMetadata.Id
        {
            get { return "201512101050527_Partner Oganization is Nullable in Outreach"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
