// <auto-generated />
namespace RSPNMISv2.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class _11232015PO_DistrictsTableRenamedProjectDistricts : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_11232015PO_DistrictsTableRenamedProjectDistricts));
        
        string IMigrationMetadata.Id
        {
            get { return "201511230915252_11232015 PO_Districts Table Renamed ProjectDistricts"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
